### ISSUE TITLE
Cannot build 4swordshax

### ISSUE THREAD

**Issue by khang06** [yellows8/dsi#3]
When trying to build, I get this:

`sudo mount -o loop 4B513945hax.savedata 4swordshax
mount: mount point 4swordshax does not exist
Makefile:28: recipe for target 'all.dat' failed
make: *** [all.dat] Error 32`

It only outputs 4B513945hax.savedata, 4swordshax.elf, and all.dat.

**Comment by yellows8** [comment]
You must create the 4swordshax directory it tried to use.

**Comment by khang06** [comment]
Thanks! It worked, but where do I get the DSi SD key? (probably console-specific)

**Comment by yellows8** [comment]
It's included with a certain public tool but it could also be determined with 3DS ITCM data.

**Comment by khang06** [comment]
So it's not console-specific? In that case, I can just grab it from my 3DS ITCM. Where is the required data located?

Edit: Never mind, got it.
